### ISSUE TITLE
tlv/keysend lnurl-pay

### ISSUE THREAD

**Issue by sputn1ck** [fiatjaf/lnurl-rfc#45]
I think having a standard for static tlv/keysend invoices could be cool.

Additionally to the standard lnurl-pay data the lnurl-pay-tlv data could contain:

- destination pubkey

- list of tlv payloads, such as fixed ones (userid) and maybe optional ones like custom donation messages

This would basically eliminate the 2 roundtrips of lnurl-pay as all of the above information is enough to have the same information

**Comment by fiatjaf** [comment]
I see what you mean. A QR code from which the wallet would extract the information necessary to build and send a keysend payment with custom records. That is indeed something that is missing from the keysend environment to make it usable beyond nerds typing CLI commands on their lnds to donate to other nodes. This would make a better tlvshop.com.

But I don't see how it fits lnurl. lnurl implies, as the name says, the wallet communicating with an URL. It would be better suited as its own protocol, maybe with custom data encoded as a sequence of tags in a weird binary format like BOLT11.

Also, the idea of having custom fields the user can edit and basically turning your wallet into a powerful interface to external apps is an interesting one and I personally like it, but currently I think the consensus is that it's too complicated and probably not worth implementing. I hope we'll get to that with lnurl-pay later.

![photo_2020-06-18_21-59-30](https://user-images.githubusercontent.com/1653275/85085599-b9ed8b80-b1ae-11ea-9659-9d74fe1a4c56.jpg)

**Comment by sputn1ck** [comment]
I get your points. However,

- Callback/Fallback urls could still be supported (but wouldn't need to be)
- A BOLT11 or similiar standard will probably not emerge for a long time.
- Implementing keysend should be easy for all c-lightning and lnd based wallets.

**Comment by sputn1ck** [comment]
Now that c-lightning natively supports keysend, it could make sense to revisit this issue again.

The only disadvantage keysend has to lnurl-pay is a missing proof of payment. However I don't see why you would need a proof of payment for things like feeding chickens, paying a donation or buying a pixel. 

The privacy advantages and ease of use/integrating makes keysend much more attractive than lnurl-pay.

**Comment by hsjoberg** [comment]
I'm not sure if keysend with lnurl makes much sense. Could you provide a real usecase over using lnurl-pay with BOLT11 invoices?

Keysend is very interesting, but it does not give a proof of payment as the sender is responsible for generating the preimage. This also makes it incompatible with lnurl-pay which mandates `payAction` things to be encrypted by the preimage.

A QR-code/protocol for keysend or similar is needed to make it useful, but it doesn't seem to fit very well with lnurl.
