### ISSUE TITLE
Change lightning: to lnurl: for App URL Schemes

### ISSUE THREAD

**Issue by jackeveritt** [fiatjaf/lnurl-rfc#53]
By recommending that `lightning:` is used to open LNURLs for apps, it causes a clash with apps that don't or never will support LNURL, but use the `lightning:` scheme.

For example, Bottle Pay probably won't support LNURL (at least initially). And on iOS, if Bottle Pay is the last app that is installed with the `lightning:` scheme, any web pages or apps on the device will redirect to Bottle Pay by default, with no option to change the default behaviour in the operating system.

On Android the user can change default behaviour, but its buried in the OS settings and is a customer support issue that could be avoided.

Perhaps the scheme should be `lnurl:` to avoid this.

**Comment by hsjoberg** [comment]
This is addressed in [LUD-17](https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md).
