### ISSUE TITLE
Domain name used in LNURL-auth is not clear

### ISSUE THREAD

**Issue by dpad85** [fiatjaf/lnurl-rfc#55]
According to the [LNURL auth specs](https://github.com/btcontract/lnurl-rfc/blob/fc901cdab19ca220f1e568333d79893e90446ec5/lnurl-auth.md) the key used by the `wallet` for signing the `k1` secret should be specific to the `service`, using the `service` domain name. However the spec is not clear whether the key should be generated with the complete `service` domain name including subdomains, or the top domain name.

**Wallet uses subdomains**

The `service` may internally use a subdomain for everything LNURL related, like `api.service.com`. In that case the account will be forever coupled to whatever internal architecture the service is currently using. If the `service` architecture changes, the `wallet` will use a different signing key, effectively creating a new account and locking the user out of his previous one.

**Wallet uses top domain only**

If there are several services on the same top domain, then the signing key would be the same for all these services. Yet, regarding security, each service maintains its own `k1` secrets and will reject any authentication attempts using `k1` secrets it has not solicited. That is, if you have 2 services, one for testnet on `api.testnet.service.com` and one for mainnet on `api.mainnet.service.com`, one cannot sign-in to `mainnet` using a signature valid on `testnet`.

Regarding privacy, the account public key is the same for every services on a top domain, and someone operating 2 of those services would know that it's the same user. But that will happen anyway, even if we use subdomains, as soon as the user provide a LN invoice to the service (containing the node public key).

So, in any case I think the spec should be clear on this, and should recommend one option or the other. I think using top domain is the better option, with subdomains the risk of being locked out is too great.

**Comment by btcontract** [comment]
Indeed this is an important point which has to be clarified. Historically a full path with subdomains is used in BLW, is it the same in phoenix?

**Comment by dpad85** [comment]
In Phoenix we use the top domain for now. @fiatjaf made a [PR ](https://github.com/ACINQ/phoenix/pull/92) to change that to subdomains, which was merged, but now I'm thinking that might not be a such a good idea.

**Comment by btcontract** [comment]
I'm more inclined to full subdomain option for the following reasons:

- privacy is slightly better if user never provides an invoice (also maybe future blinding improvements can help here).

- UX is more clear (in PR example user may differentiate easily between `filemarket.bigsun.xyz` and `lnurl.bigsun.xyz` which may be important).

- as far as I understand top level domains are things like `.com`, '.io' and `site.com` is second-level-domain so we'd have to introduce a more complex and rather arbitrary rule (up to second subdomain or something like that).


As to PR, this change in Phoenix will lock users out of services which use 3rd-level subdomains already, most notably lnmarkets (api.lnmarkets.com).

**Comment by fiatjaf** [comment]
If we have to use top-level domains then suddenly wallets must agree on what is a top-level domain and keep lists of top-level domains.

For example, all Brazilian websites are something.com.br. Are wallets going to use com.br for everybody? They will have know all the details of how each TLD is distributed.

If ICANN creates new TLDs wallets will have to he updated. If someone wanted to use a .bit domain that won't work. There are many issues.

**Comment by btcontract** [comment]
@fiatjaf sounds very reasonable.

@dpad85 I guess the best course of action is to proceed with PR but make a manual exception for lnmarkets?

**Comment by dpad85** [comment]
Sorry for the confusion regarding the "top domain" naming I used.

> If we have to use top-level domains then suddenly wallets must agree on what is a top-level domain and keep lists of top-level domains.

There's already a list for public suffixes since it's a problem for cookies as well, so you can quite easily retrieve the effective TLD + 1 and get to the actual service's domain name. Brazilian service `api.service.com.br` would be authenticated on as `service.com.br`. That's what I'm doing already on Phoenix.

> As to PR, this change in Phoenix will lock users out of services which use 3rd-level subdomains already, most notably lnmarkets (api.lnmarkets.com).

Yes that's what made me think about it. Any changes to the `service` domain invalidates previous keys which was not obvious to me when reading the specs.

> UX is more clear (in PR example user may differentiate easily between filemarket.bigsun.xyz and lnurl.bigsun.xyz which may be important).

You can always display the full URL to the user before authenticating, and sign using the "top domain" (eTLD + 1). Though I would say that URLs for authentication APIs including subdomains can be a bit esoteric and not make much sense to the user.

**Comment by fiatjaf** [comment]
> You can always display the full URL to the user before authenticating, and sign using the "top domain" (eTLD + 1). Though I would say that URLs for authentication APIs including subdomains can be a bit esoteric and not make much sense to the user.

Wouldn't it make more sense to use the full domain name internally but show only the top part to the user then so they have a less confusing experience but the simplicity of the protocol and compatibility across wallets is ensured?

(Actually I think this was the reason my PR didn't include a change in the UI, only in the internal name used in the key generation process.)

---

That list to me looks more like a best-effort UI helper than something that should be relied upon by a protocol that is supposed to be supported by multiple wallets. It contains lots (and lots) of somewhat arbitrary public suffixes like `zapto.xyz`, which are dependent solely on the choice of the temporary owner of `zapto.xyz` to allow people to register subdomains on his domain.

What happens if that public list of suffixes go down? Someone else will come up with a new list that will probably be different. I don't know, I would be very wary of including that extra complexity in the protocol.

**Comment by fiatjaf** [comment]
Also that list doesn't include weird domain names that at least I personally hope will win over ICANN in the future. `.bit` is a failed example, but even it should be supported if the user has somehow managed to configure its phone to connect to a DNS server that understands it, but that list does not include `.bit` and will likely not include `.fiatjaf` or whatever else anyone may invent. Even if this paragraph sounds silly I think the protocol must be left open in this sense.

**Comment by btcontract** [comment]
I definitely like a self-contained option more, relying solely on provided domain name is simple and compatible with any future changes.

Meaningless and changing subdomains can be an issue but I think we can mitigate it with clear instructions both for wallets and services.

**Comment by btcontract** [comment]
Attempted to clarify this in https://github.com/btcontract/lnurl-rfc/pull/56
