### ISSUE TITLE
LNURL tag query parameter

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [fiatjaf/lnurl-rfc#72]
The Readme mentions:

> Once LNURL is decoded:
> - If tag query parameter is present then this LNURL has a special meaning, further actions will be based on tag parameter value.
> - Otherwise a GET request should be executed which must return a JSON object containing a tag field, further actions will be based on tag field value.

Does the first point mean the original URL encoded in the QR code can contain `tag=withdrawRequest` and then the wallet can skip the first HTTP GET and get all the other parameters from the original URL?

In this case the URL in the QR code would also have callback, k1, defaultDescription, minWithdrawable, maxWithdrawable query parameters?

So the withdraw flow would be:

1. User scans a LNURL QR code and LN WALLET decodes LNURL.

LN WALLET gets callback, k1, defaultDescription, minWithdrawable, maxWithdrawable from url query params

3. LN WALLET Displays a withdraw dialog where user can specify an exact sum to be withdrawn which would be bounded by:

[...]

This is not mentioned on the LNURL-withdraw page or the other pages. It would save one round trip of HTTP but is it actually supported by wallets?

**Comment by fiatjaf** [comment]
It is mentioned as the "fast" withdraw method, which shouldn't be used in QR codes, only links. And wallet support is optional since the server must provide the params through the URL anyway in case the wallet asks.

**Comment by pvyhnal-generalbytes** [comment]
Thanks, I overlooked the "fast" withdraw section because it says _It is not suitable for QR code implementations._ 

Why is it not suitable for QRs, if a new QR would be generated for every new withdrawal?
